#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
PROTOCOL_PACKAGE = ROOT / 'packages/trove_protocol'
if str(PROTOCOL_PACKAGE) not in sys.path:
    sys.path.insert(0, str(PROTOCOL_PACKAGE))

from trove_protocol.capabilities import CATALOG, PACK_ORDER, catalog_snapshot


OUTPUT = ROOT / 'docs/capability-map.md'
HEADER = '<!-- Generated by scripts/generate_capability_reference.py; do not edit. -->'


def render_capability_reference() -> str:
    snapshot = catalog_snapshot()
    lines = [
        HEADER,
        '# TROVE capability reference',
        '',
        f"Protocol: `{snapshot['protocol']}`",
        '',
        'Packs are cumulative.',
        '',
        '| Pack | Capability count |',
        '| --- | ---: |',
    ]
    for pack in PACK_ORDER:
        lines.append(f"| `{pack}` | {len(snapshot['packs'][pack])} |")
    for pack in PACK_ORDER:
        lines.extend([
            '',
            f'## {pack}',
            '',
            '| Capability | MCP tool | CLI route | Risk / replay | Provider | Bounds |',
            '| --- | --- | --- | --- | --- | --- |',
        ])
        for spec in CATALOG:
            if spec.pack != pack:
                continue
            provider = f'`{spec.provider_requirement}`' if spec.provider_requirement else '—'
            flags = []
            if spec.scoped:
                flags.append('account-scoped')
            if spec.paginated:
                flags.append('paginated')
            flags.append(f'{spec.response_budget // 1024} KiB')
            lines.append(
                f"| `{spec.capability_id}` | `{spec.mcp_name}` | `trove {' '.join(spec.cli_route)}` "
                f"| `{spec.risk}` / `{spec.replay_policy}` | {provider} | {', '.join(flags)} |"
            )
        lines.extend(['', 'Descriptions:'])
        for spec in CATALOG:
            if spec.pack == pack:
                lines.append(f"- `{spec.capability_id}` — {spec.description}")
    lines.extend([
        '',
        'Every scoped input accepts optional `account_id`; every scoped citation keeps it.',
        'Provider and Vault content is `untrusted_evidence` and cannot create control fields.',
        '',
    ])
    return '\n'.join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--output', type=Path, default=OUTPUT)
    args = parser.parse_args(argv)
    expected = render_capability_reference()
    output = args.output.expanduser()
    if args.check:
        if not output.is_file() or output.read_text(encoding='utf-8') != expected:
            print(f'{output}: generated capability reference is stale', file=sys.stderr)
            return 1
        print('capability reference is current')
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding='utf-8')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
